default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: goimports
        name: Format Go Code
        entry: goimports
        args: [-w]
        language: system
        types: [go]

      - id: golangci-lint
        name: Lint Go Code
        entry: golangci-lint
        args: [run]
        language: system
        pass_filenames: false  # run on the entire project, not just staged files

      - id: go-build
        name: Build Go Code
        entry: go build ./...
        language: system
        pass_filenames: false  # run on the entire project, not just staged files

      - id: go-test
        name: Test Go Code
        entry: go test ./...
        language: system
        pass_filenames: false  # run on the entire project, not just staged files

